server:
  port: 8189
  servlet:
    context-path: /nya
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5455/nya_db
    username: nya
    password: nya777
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    ru.fomin.nyakashop.controllers: INFO
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 30
      file-name-pattern: logs/app-%d{yyyy-MM-dd-HH-mm}.%i.log

pageSize:
  product: 2
  order: 5
formatter:
  dateTime: 'dd.MM.yyyy HH:mm'
cart:
  prefix: NYAKA_CART_
jwt:
  lifetime: 3600_000
  secret: 8EF282C6480E566308064F90C371BE2CD7822B3D9E66A0083B989B2477D89A7E
minio:
  ip: localhost
  user: root
  password: password
  port: 9000
  bucket: test
  partSize: 5_243_000
paypal:
  client-id: Acj0d1EQ7M1m-jY5JR68soIwsV00zBmsr-30FtM2oATOFDfWSOeLZ_Tv4UIRmdGiKljYrzudGGfLD7SP
  client-secret: EJwZ4ErSs--V_rIxPRJWZ8P238rh4o-yOO-QvWhAHWxVME3KkxV0DY2ZpZUx77UKPBjiRZ4XFeebIp6j
  mode: sandbox
