server:
  port: 8189
  servlet:
    context-path: /nya
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5455/nya_db
    username: nya
    password: nya777
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true

pageSize: 2
formatter:
  dateTime: 'dd.MM.yyyy HH:mm'
jwt:
  lifetime: 3600000
  secret: 8EF282C6480E566308064F90C371BE2CD7822B3D9E66A0083B989B2477D89A7E